@section('description', $description)
@section('keywords', "$key,$title,$description,$base_keyworlds->value")
@section('subject', $subject)
@section('og_title', $subject)
@section('topic', $subject)
@section('designer', 'شرکت طراحی سایت طرحفا')
@section('url', asset(''))
@section('canonical', asset(''))
@section('site_name', $title)
@section('og_description', $description)
@section('brand', $title)
@section('type', 'website')
